version: '3.5'
services:
    loterioma_builder:
        build: .docker/worker
        container_name: loterioma_builder
        stdin_open: true
        tty: true
        ports:
          - 9904:80
        networks:
          - proxynet

networks:
    proxynet:
        name: loterioma-net
        driver: bridge